export type ItemUnit = 'each' | 'kg' | 'litre' | 'box' | 'case'
export type LocationType = 'warehouse' | 'shop' | 'van' | 'quarantine'

export const ITEM_UNITS: ItemUnit[] = ['each', 'kg', 'litre', 'box', 'case']
export const LOCATION_TYPES: LocationType[] = ['warehouse', 'shop', 'van', 'quarantine']

export interface Item {
  id: string
  sku: string
  name: string
  category: string | null
  unit: ItemUnit
  units_per_case: number
  barcode: string | null
  unit_cost: number | null
  sell_price: number | null
  supplier_id: string | null
  moq: number
  target_cover_days: number
  service_level: number
  manual_reorder_point: number | null
  velocity_window_days: number
  exclude_from_reorder: boolean
  is_tracked: boolean
  is_active: boolean
  is_serialized: boolean
}

export interface Location {
  id: string
  code: string
  name: string
  type: LocationType
  is_active: boolean
}

export interface Supplier {
  id: string
  name: string
  contact_name: string | null
  contact_email: string | null
  phone: string | null
  lead_time_days: number | null
  currency: string
  notes: string | null
  is_active: boolean
}

/**
 * The SKU prefix is chosen at creation; the numeric part is generated by
 * next_sku() in migration 0003. Asking someone to type a whole SKU produces
 * rejections against the format constraint — generating it produces
 * compliance instead (§4.1).
 */
export const SKU_PREFIX_PATTERN = /^[A-Z]{2,6}$/
